### ISSUE TITLE
Tree handle is sometimes nil

### ISSUE THREAD

**Issue by expipiplus1** [julienvincent/hunk.nvim#13]
To reproduce:

- Use this plugin with `jj split`
- When it opens, observe that the tree view is focused and the first file is displayed
- Move to this file buffer without pressing `<CR>` in the tree view, either by clicking or navigating to the next split
- Try to add some changes with `a` or `A`
- Observe this error:

```php
E5108: Error executing lua: ...e/.local/share/astrovim/lazy/hunk.nvim/lua/hunk/init.lua:106: attempt to index upvalue 'tree' (a nil value)
stack traceback:
        ...e/.local/share/astrovim/lazy/hunk.nvim/lua/hunk/init.lua:106: in function 'on_event'
        ...local/share/astrovim/lazy/hunk.nvim/lua/hunk/ui/file.lua:87: in function <...local/share/astrovim/lazy/hunk.nvim/lua/hunk/ui/file.lua:85>
```

The workaround is to always change focus using <CR> in the tree view.

**Comment by julienvincent** [comment]
Thanks for the report, I'll look into this!
