### ISSUE TITLE
bug: duplicate signs

### ISSUE THREAD

**Issue by benlubas** [julienvincent/hunk.nvim#2]
For some reason the check box is duplicated in my sign column. I thought that it was b/c I use statuscol.nvim, but the issue persists when I disable the plugin.

![image](https://github.com/user-attachments/assets/1c658acc-4039-47d9-9200-21f90dca2ba5)

Even more confusing, I can get them to de-sync by just adding and removing the line or hunk

![image](https://github.com/user-attachments/assets/e9f4510c-2405-4e9e-8910-b83ac14126ad)

**Comment by julienvincent** [comment]
TIL that you can increase the width of the signcol!

So I guess you have it set to 2, in which case this behaviour makes sense with how I built it.

I'll get this fixed today

**Comment by benlubas** [comment]
Thanks for the swift reply and fix!
