### ISSUE TITLE
bug: need to nil check highlight information

### ISSUE THREAD

**Issue by benlubas** [julienvincent/hunk.nvim#8]
[this line](https://github.com/julienvincent/hunk.nvim/blob/master/lua/hunk/api/highlights.lua#L16) can fail

```lua
vim.api.nvim_set_hl(0, "HunkDiffAddAsDelete", {
  bg = string.format("#%06x", diff_delete_highlight.bg),
})
```

diff_delete_highlight is not guaranteed to have a `bg` field. For example, the default colorscheme's `DiffDelete` hl doesn't have a background.

**Comment by julienvincent** [comment]
Ok fixing this now
